version: '3.1'
services:
  wordpress:
    image: wordpress:5.8.1
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: privateipaddressofdb:3306
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 80:80
      - 443:443
volumes:
  wordpress_data: {}