version: '3.1'
services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:80
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: password
volumes:
  mysql: {}